'use strict';
const catalog=globalThis.SPT_Languages;
const $=id=>document.getElementById(id),defaults={sourceLanguage:'auto',targetLanguage:'en',enabled:true,hybridEnabled:false,hybridProvider:'studio',googleApiKey:'',lingvaInstance:'https://translate.plausibility.cloud',studioInstance:'http://localhost:5000',deeplApiKey:'',dailyCharBudget:15000};
const fields={source:'sourceLanguage',target:'targetLanguage',enabled:'enabled',hybrid:'hybridEnabled',provider:'hybridProvider',key:'googleApiKey',lingva:'lingvaInstance',studio:'studioInstance',deeplKey:'deeplApiKey',budget:'dailyCharBudget'};
let detectedLanguage='',loading=true,saveTimer,refreshTimer,saveChain=Promise.resolve();
function toggleProvider(){const local=catalog.localStudio({hybridProvider:$('provider').value,studioInstance:$('studio').value});$('budget').disabled=local;$('budgetHint').textContent=local?'Unlimited daily usage for local LocalTranslator Studio. Characters are still counted.':'Counts new text sent to external services, including failed calls.';document.querySelectorAll('.providerBox').forEach(el=>el.classList.toggle('hidden',el.id!==$('provider').value+'Box'));}
function languageHint(){const source=$('source').value,target=$('target').value,other=target!=='en';const detected=source==='auto'&&detectedLanguage&&catalog.names[detectedLanguage]?'Detected: '+catalog.names[detectedLanguage]+'. ':'';$('languageHint').textContent=source===target?'Source and target are the same. Original text is preserved.':detected+(other?'Translation uses English first, then the selected language. Enable fallback manually for missing text.':'Eight local dictionaries translate into English. Missing phrases can use fallback.');$('swapLanguages').disabled=source==='auto'&&!detectedLanguage;$('swapLanguages').title=$('swapLanguages').disabled?'Select a source or wait for page detection.':'Swap source and target';}
$('swapLanguages').onclick=()=>{const source=$('source').value==='auto'?detectedLanguage:$('source').value;if(!source)return;const target=$('target').value;$('source').value=target;$('target').value=source;languageHint();persist();};
$('retryPage').onclick=async()=>{try{if(!$('hybrid').checked){$('pageStatus').textContent='Enable Hybrid learning fallback manually to translate missing text.';return;}await persist();await chrome.runtime.sendMessage({type:'SPT_CLEAR_COOLDOWN'});const [tab]=await chrome.tabs.query({active:true,currentWindow:true});await chrome.tabs.sendMessage(tab.id,{type:'SPT_RETRY'});await refresh();}catch(e){$('pageStatus').textContent=e.message;}};
function snapshot(){const patch={};for(const [id,k]of Object.entries(fields)){const el=$(id);patch[k]=el.type==='checkbox'?el.checked:el.value.trim();}patch.dailyCharBudget=Math.max(1000,Number(patch.dailyCharBudget)||15000);patch.studioInstance||=defaults.studioInstance;patch.lingvaInstance||=defaults.lingvaInstance;return patch;}
function persist(){if(loading)return Promise.resolve();clearTimeout(saveTimer);const patch=snapshot();saveChain=saveChain.catch(()=>{}).then(async()=>{for(const k of ['studioInstance','lingvaInstance']){const u=new URL(patch[k]);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw new Error('Enter a valid HTTP(S) address.');}await chrome.storage.local.set(patch);toggleProvider();languageHint();$('saved').textContent='Saved. Changes applied to open pages.';await refresh();}).catch(e=>{$('saved').textContent='Could not save: '+e.message;});return saveChain;}
async function refresh(){const s=await catalog.loadSettings(chrome.storage.local,{...defaults,learnedExact:{},learnedByPair:{},learnedMeta:{},hybridTelemetry:{}});let page={};try{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});page=await chrome.tabs.sendMessage(tab.id,{type:'SPT_STATS'})||{};}catch{}detectedLanguage=page.detectedLanguage||'';languageHint();$('pageStatus').textContent=!page.engine?'This page cannot be translated or needs to be reopened after updating.':page.lastError?'Translation paused: '+page.lastError:page.untranslated||page.scanning?`${page.translated||0} complete${page.partiallyTranslated?' · '+page.partiallyTranslated+' partial':''} · ${page.untranslated||0} remaining${page.busy||page.scanning?' · Translating…':!s.hybridEnabled?' · Enable fallback manually for missing text.':''}`:'Page text processed.';const t=s.hybridTelemetry||{},sameDay=t.day===new Date().toISOString().slice(0,10),meta=s.learnedMeta||{};
 $('hybridBadge').textContent=s.hybridEnabled?'Fallback enabled':'Local';$('learnedStat').textContent=catalog.learnedCount(s).toLocaleString('en-US');$('fallbackStat').textContent=(meta.day===new Date().toISOString().slice(0,10)?meta.charsToday||0:0).toLocaleString('en-US');$('providerStat').textContent=s.hybridEnabled?({studio:'Studio',google:'Google Cloud',deepl:'DeepL',lingva:'Lingva'}[s.hybridProvider]||'Studio'):'Local';$('fallbackStatusStat').textContent=!sameDay?'Waiting':({ok:'Connected',error:'Failed',requesting:'Translating…',idle:'Waiting'}[t.status]||'Waiting');for(const l of catalog.dictionaries)$(l+'Stat').textContent=page[l]?.toLocaleString('en-US')||'—';$('technical').textContent=`Local bilingual entries: ${(page.localPairs||0).toLocaleString('en-US')} · Route: ${page.translationRoute||'English first'} · Cache: ${page.cache||0} · Requests: ${sameDay?t.requestsToday||0:0} · HTTP: ${t.lastHttpStatus||'—'} · ${t.lastDurationMs||0} ms`;$('translationDiagMessage').textContent=page.lastWarning||t.lastError||'No errors recorded.';if(!page.engine)$('translationDiagMessage').textContent+='\nThis tab does not allow translation or needs to be reopened after installing the extension.';}
for(const [id]of Object.entries(fields)){const el=$(id);el.addEventListener('change',()=>{toggleProvider();languageHint();persist();});if(!['enabled','hybrid','provider','source','target'].includes(id))el.addEventListener('input',()=>{clearTimeout(saveTimer);saveTimer=setTimeout(persist,450);});}
$('diagnoseBtn').onclick=async()=>{const button=$('diagnoseBtn');button.disabled=true;$('connectionDiagMessage').textContent='Testing…';try{await persist();const r=await chrome.runtime.sendMessage({type:'SPT_HYBRID_DIAGNOSE'}),d=r?.diagnostics;if(!r?.ok||!d)throw new Error(r?.error||'No diagnostics returned');const h=d.health,t=d.translation;$('connectionDiagMessage').textContent=`Pair: ${d.source||'zh'} → ${d.target||'en'}\nServer: ${h.ok?'OK':'failed'}${h.count?' · '+h.count+' languages':''}\nTranslation: ${t.ok&&t.translation?(d.text||'你好')+' → '+t.translation:(t.error||t.apiError||t.response||'failed')}\n${t.durationMs||0} ms`+(d.languages?`\nInstalled languages: ${d.languages.map(x=>x.code).join(', ')}`:'')+(d.instances?`\n\n${d.selectedInstance?'Working instance: '+d.selectedInstance:'All instances failed. Use local LocalTranslator Studio.'}\n${d.instances.map(x=>new URL(x.instance).host+': '+x.translation.reason).join('\n')}`:'');}catch(e){$('connectionDiagMessage').textContent=e.message;}finally{button.disabled=false;await refresh();}};
$('export').onclick=async()=>{try{const r=await chrome.runtime.sendMessage({type:'SPT_EXPORT_LEARNED'});if(!r?.ok)throw new Error(r?.error||'Export failed');}catch(e){$('saved').textContent=e.message;}};
$('import').onclick=()=>$('importFile').click();
function validPairs(obj,maxKey=1200){if(!obj||typeof obj!=='object'||Array.isArray(obj))throw new Error('Invalid dictionary');const result={};for(const [k,v]of Object.entries(obj)){if(['__proto__','constructor','prototype'].includes(k)||!k.trim()||k.length>maxKey||typeof v!=='string'||!v.trim()||v.length>4000)throw new Error('Invalid entry');result[k]=v;}if(Object.keys(result).length>50000)throw new Error('Maximum 50,000 entries per import');return result;}
$('importFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>15*1024*1024)throw new Error('File exceeds 15 MB');const data=JSON.parse(await file.text()),patch={};if(data.entries){const s=await chrome.storage.local.get({learnedExact:{},learnedMeta:{}});const entries=validPairs(data.entries);patch.learnedExact={...s.learnedExact,...entries};const keys=Object.keys(patch.learnedExact);while(keys.length>8000)delete patch.learnedExact[keys.shift()];patch.learnedMeta={...s.learnedMeta,order:keys};}if(data.pairs){const s=await chrome.storage.local.get({learnedByPair:{}}),pairs=validPairs(data.pairs,1232);for(const key of Object.keys(pairs)){const match=key.match(/^([a-z]+)>([a-z]+)\0(.+)$/s);if(!match||(match[1]!=='auto'&&!catalog.names[match[1]])||!catalog.names[match[2]])throw new Error('Invalid language pair');}patch.learnedByPair={...s.learnedByPair,...pairs};const keys=Object.keys(patch.learnedByPair);while(keys.length>8000)delete patch.learnedByPair[keys.shift()];}if(data.dictionaries){const normalized={};for(const [key,value] of Object.entries(data.dictionaries))normalized[catalog.normalize(key)]=value;for(const l of catalog.dictionaries)if(normalized[l]){const k='custom'+l[0].toUpperCase()+l.slice(1),s=await chrome.storage.local.get({[k]:{}});patch[k]={...s[k],...validPairs(normalized[l])};}}if(!Object.keys(patch).length)throw new Error('JSON has no entries or dictionaries');await chrome.storage.local.set(patch);$('saved').textContent='Imported and applied to open pages.';await refresh();}catch(e){$('saved').textContent='Import failed: '+e.message;}finally{e.target.value='';}};
chrome.storage.onChanged.addListener(()=>{clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>refresh().catch(console.debug),250);});
(async()=>{const s=await catalog.loadSettings(chrome.storage.local,defaults);for(const [id,k]of Object.entries(fields)){if($(id).type==='checkbox')$(id).checked=!!s[k];else $(id).value=['source','target'].includes(id)?catalog.normalize(s[k]):s[k];}toggleProvider();languageHint();loading=false;await refresh();})().catch(e=>{$('saved').textContent=e.message;});

setInterval(()=>refresh().catch(console.debug),1500);
